### ISSUE TITLE
ripd.c:2308:10: error: this ‘if’ clause does not guard this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’

### ISSUE THREAD

**Issue by jean-christophe-manciot** [CumulusNetworks/quagga#22]
git sources commit 83d8f4f7d1d634af3ab389596add99dd9973f7c7
```
        echo --------
        echo Cleaning
        echo --------
        chown -R actionmystique:actionmystique *
        cd git-quagga-cumulus
        git-reset-clean-pull-checkout.sh $branch $tag

        echo ---------------------------
        echo Checking Build Dependencies
        echo ---------------------------
        check-build-dependencies.sh

        echo --------
        echo Building
        echo --------
        dpkg-buildpackage -b -m"Jean-Christophe Manciot <manciot.jeanchristophe@gmail.com>"
```
leads to:
```
make[4]: Entering directory '/home/actionmystique/Program-Files/Ubuntu/Quagga/git-quagga-cumulus/ripd'
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=\"/etc/quagga/\" -I. -I..  -I.. -I.. -I../lib -I../lib  -Werror -g -O2 -g -Os -fno-omit-frame-pointer -Wall -Wextra -Wmissing-prototypes -Wmissing-declarations -Wpointer-arith -Wbad-function-cast -Wwrite-strings -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -MT rip_memory.o -MD -MP -MF .deps/rip_memory.Tpo -c -o rip_memory.o rip_memory.c
mv -f .deps/rip_memory.Tpo .deps/rip_memory.Po
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=\"/etc/quagga/\" -I. -I..  -I.. -I.. -I../lib -I../lib  -Werror -g -O2 -g -Os -fno-omit-frame-pointer -Wall -Wextra -Wmissing-prototypes -Wmissing-declarations -Wpointer-arith -Wbad-function-cast -Wwrite-strings -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -MT ripd.o -MD -MP -MF .deps/ripd.Tpo -c -o ripd.o ripd.c
ripd.c: In function ‘rip_output_process’:
ripd.c:2308:10: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
          if (IS_RIP_DEBUG_PACKET)
          ^~
ripd.c:2311:5: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
     continue;
     ^~~~~~~~
cc1: all warnings being treated as errors
Makefile:538: recipe for target 'ripd.o' failed
make[4]: *** [ripd.o] Error 1
```
Whole log: [build-error.txt](https://github.com/CumulusNetworks/quagga/files/717290/build-error.txt)
.

**Comment by jean-christophe-manciot** [comment]
A quick workaround:
```
        # Warnings not treated as errors otherwise it does not compile
        sed -i 's|WERROR="-Werror"|WERROR=""|g' configure.ac
```

**Comment by donaldsharp** [comment]
@jean-christophe-manciot The issue is that our debian build packaging has --enable-werror=yes.  Remove that line from it and rebuild.

What is going on is that the gcc compiler is frequently different amongst different platforms and gives different warnings.  On the version of the compiler we build with gcc version 4.9.2 (Debian 4.9.2-10) we do not experience warnings to be turned into errors.
